version: "3.3"

services:
  redis:
    image: extvos/redis:latest
    environment:
      REDIS_PROTECTED_MODE: "no"
      REDIS_DATABASE: 24
      REDIS_PASSWORD: 'quickstart.extvos'
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"

  postgresql:
    image: extvos/postgresql:latest
    environment:
      REPLICATION_ROLE: master
      POSTGRES_DB: quickdb
      POSTGRES_PASSWORD: 'quickstart.extvos'
      TZ: Asia/Shanghai
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  emqx:
    image: extvos/emqx:latest
    environment:
      TZ: Asia/Shanghai
    ports:
      - "1883:1883"
#      - "8081:8081"
#      - "8083:8083"
#      - "8883:8883"
      - "18083:18083"

  clickhouse:
    image: yandex/clickhouse-server
    volumes:
      - "./data/clickhouse:/var/lib/clickhouse"
      - "./data/log:/var/log"
    ulimits:
      nofile: 262144
    ports:
      - 9000:9000
      - 9009:9009
      - 8123:8123
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: 'quickstart.extvos'
      TZ: Asia/Shanghai

  quick-demo:
    image: java:8
    depends_on:
      - postgresql
      - redis
    environment:
      SERVICE_NAME: quick-demo
      SERVER_PORT: 8080
      POSTGRES_HOST: postgresql
      POSTGRES_DATABASE: quickdb
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 'quickstart.extvos'
      REDIS_HOST: redis
      REDIS_DATABASE: 1
      REDIS_PASSWORD: 'quickstart.extvos'
      AUTH_BASE_URL: http://work.cygnux.cn
    volumes:
      - "./data/log:/var/log"
      - "./data/files:/home/data"
      - "./demo/target/quick-demo-app-0.0.1-SNAPSHOT.jar:/home/boot.jar"
    command: ["java", "-jar", "/home/boot.jar"]

  nginx:
    image: extvos/nginx:latest
    depends_on:
      - quick-demo
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "./nginx/sites.d:/etc/nginx/sites.d"
      - "./nginx/cert:/etc/nginx/cert"
      - "./data/files:/home/data"
      - "./data/log:/var/log/nginx"
      - "./htmldocs:/var/lib/nginx/html"
    ports:
      - "80:80"
      - "443:443"
